
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Surface\Documents\Projects\PDFUtilityRedux\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("180x600")
window.configure(bg = "#D0D0D0")


canvas = Canvas(
    window,
    bg = "#D0D0D0",
    height = 600,
    width = 180,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    178.0,
    -1.0,
    179.0000228881836,
    600.0,
    fill="#BCBEC0",
    outline="")
window.resizable(False, False)
window.mainloop()
